apiVersion: v1
kind: Service
metadata:
  name: devops-task-service
spec:
  type: LoadBalancer
  selector:
    app: devops-task-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      protocol: TCP
